/* OneDrive sync uses Microsoft Graph's private App Folder permission. */
(() => {
  const SETTINGS='property-ledger-onedrive-settings-v1', FILE='property-ledger-data.json';
  let settings=JSON.parse(localStorage.getItem(SETTINGS)||'{}'), token=''; let syncing=false, timer;
  const $=s=>document.querySelector(s), status=message=>$('#cloudStatus').textContent=message;
  const saveSettings=()=>localStorage.setItem(SETTINGS,JSON.stringify(settings));
  function snapshot(){return {version:1,updatedAt:new Date().toISOString(),data,forecasts};}
  function redirectUri(){return `${location.origin}${location.pathname}`;}
  function makeVerifier(){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';return Array.from(crypto.getRandomValues(new Uint8Array(64)),x=>chars[x%chars.length]).join('')}
  async function sha256(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest('SHA-256',bytes);return btoa(String.fromCharCode(...new Uint8Array(hash))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  async function exchange(code){const verifier=sessionStorage.getItem('pl-onedrive-verifier');const body=new URLSearchParams({client_id:settings.clientId,grant_type:'authorization_code',code,redirect_uri:redirectUri(),code_verifier:verifier});const r=await fetch('https://login.microsoftonline.com/consumers/oauth2/v2.0/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Microsoft could not complete sign-in. Check the Application ID and redirect URL.');return r.json()}
  async function finishLogin(){const q=new URLSearchParams(location.search),code=q.get('code'),error=q.get('error');if(!code&&!error)return;if(error){status(`Microsoft sign-in was cancelled: ${q.get('error_description')||error}`);history.replaceState({},'',location.pathname);return}try{const result=await exchange(code);token=result.access_token;settings.connected=true;saveSettings();history.replaceState({},'',location.pathname);await download()}catch(e){status(e.message)} }
  async function graph(path,options={}){if(!token)throw Error('Please connect to OneDrive first.');const r=await fetch(`https://graph.microsoft.com/v1.0${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});if(!r.ok)throw Error(r.status===404?'No cloud data has been saved yet.':`OneDrive request failed (${r.status}).`);return r}
  async function upload(){if(!token||syncing)return;syncing=true;try{status('Saving to OneDrive…');await graph(`/me/drive/special/approot:/${FILE}:/content`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot())});status('Synced to OneDrive.');}catch(e){status(e.message)}finally{syncing=false}}
  async function download(){try{status('Downloading latest OneDrive data…');const r=await graph(`/me/drive/special/approot:/${FILE}:/content`);const cloud=await r.json();if(!cloud?.data?.properties||!Array.isArray(cloud.forecasts))throw Error('The OneDrive file is not valid Property Ledger data.');data=cloud.data;forecasts=cloud.forecasts;localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem(forecastKey,JSON.stringify(forecasts));renderAll();renderForecasts();status(`Downloaded cloud data saved ${new Date(cloud.updatedAt).toLocaleString('en-GB')}.`)}catch(e){status(e.message)}}
  async function connect(){settings.clientId=$('#cloudClientId').value.trim();if(!settings.clientId)return status('Paste the Microsoft Application (client) ID first.');saveSettings();const verifier=makeVerifier();sessionStorage.setItem('pl-onedrive-verifier',verifier);const challenge=await sha256(verifier);const params=new URLSearchParams({client_id:settings.clientId,response_type:'code',redirect_uri:redirectUri(),response_mode:'query',scope:'openid profile offline_access User.Read Files.ReadWrite.AppFolder',code_challenge:challenge,code_challenge_method:'S256'});location.assign(`https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?${params}`)}
  window.cloudSync={queue(){if(!token)return;clearTimeout(timer);timer=setTimeout(upload,700)}};
  $('#oneDriveSync').onclick=()=>{$('#cloudClientId').value=settings.clientId||'';$('#cloudActions').hidden=!settings.connected;status(settings.connected?'Connected to OneDrive. Changes sync automatically.':'Connect your Microsoft account to keep this app updated across devices.');$('#cloudDialog').showModal()};
  $('#cloudDialog .close').onclick=()=>$('#cloudDialog').close();$('#cloudConnect').onclick=connect;$('#cloudUpload').onclick=upload;$('#cloudDownload').onclick=download;$('#cloudDisconnect').onclick=()=>{token='';settings={};saveSettings();$('#cloudActions').hidden=true;status('Disconnected. Local data remains on this device.')};
  finishLogin();
})();
