/* Google Drive sync: data is saved in the private appDataFolder, not My Drive. */
(() => {
  const SETTINGS='property-ledger-google-drive-settings-v1', FILE='property-ledger-data.json', SCOPE='https://www.googleapis.com/auth/drive.appdata';
  let settings=JSON.parse(localStorage.getItem(SETTINGS)||'{}'), token='', syncing=false, timer, client;
  const $=s=>document.querySelector(s), status=message=>$('#cloudStatus').textContent=message;
  const saveSettings=()=>localStorage.setItem(SETTINGS,JSON.stringify(settings));
  const snapshot=()=>({version:1,updatedAt:new Date().toISOString(),data,forecasts});
  async function api(url,options={}){if(!token)throw Error('Connect Google Drive first.');const r=await fetch(url,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});if(!r.ok)throw Error(r.status===401?'Your Google sign-in has expired. Connect Google Drive again.':r.status===404?'No cloud data has been saved yet.':`Google Drive request failed (${r.status}).`);return r}
  async function findFile(){const q=encodeURIComponent(`name='${FILE}' and 'appDataFolder' in parents and trashed=false`);const r=await api(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=appDataFolder&fields=files(id)`);const result=await r.json();return result.files?.[0]?.id}
  async function upload(){if(!token||syncing)return;syncing=true;try{status('Saving to Google Drive…');const id=await findFile(),body=JSON.stringify(snapshot());if(id){await api(`https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body});}else{const boundary='propertyledgerboundary';const multipart=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name:FILE,parents:['appDataFolder'],mimeType:'application/json'})}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${body}\r\n--${boundary}--`;await api('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body:multipart});}status('Synced to Google Drive.');}catch(e){status(e.message)}finally{syncing=false}}
  async function download(){try{status('Downloading latest Google Drive data…');const id=await findFile();if(!id)throw Error('No cloud data has been saved yet. Use Upload now on your first device.');const r=await api(`https://www.googleapis.com/drive/v3/files/${id}?alt=media`);const cloud=await r.json();if(!cloud?.data?.properties||!Array.isArray(cloud.forecasts))throw Error('The Google Drive file is not valid Property Ledger data.');data=cloud.data;forecasts=cloud.forecasts;localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem(forecastKey,JSON.stringify(forecasts));renderAll();renderForecasts();status(`Downloaded cloud data saved ${new Date(cloud.updatedAt).toLocaleString('en-GB')}.`);}catch(e){status(e.message)}}
  function loadGoogle(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=resolve;script.onerror=()=>reject(Error('Could not load Google sign-in. Check your internet connection.'));document.head.append(script)})}
  async function connect(){settings.clientId=$('#cloudClientId').value.trim();if(!settings.clientId)return status('Paste the Google OAuth Client ID first.');try{await loadGoogle();settings.connected=true;saveSettings();client=google.accounts.oauth2.initTokenClient({client_id:settings.clientId,scope:SCOPE,callback:async response=>{if(response.error)return status(`Google sign-in failed: ${response.error}`);token=response.access_token;$('#cloudActions').hidden=false;status('Connected to Google Drive. Choose Download latest or Upload now.');}});client.requestAccessToken({prompt:'consent'});}catch(e){status(e.message)}}
  window.cloudSync={queue(){if(!token)return;clearTimeout(timer);timer=setTimeout(upload,700)}};
  $('#oneDriveSync').onclick=()=>{$('#cloudClientId').value=settings.clientId||'';$('#cloudActions').hidden=!token;status(token?'Connected to Google Drive. Changes sync automatically.':settings.connected?'Connect Google Drive for this session, then download the latest copy.':'Connect your Google account to keep this app updated across devices.');$('#cloudDialog').showModal()};
  $('#cloudDialog .close').onclick=()=>$('#cloudDialog').close();$('#cloudConnect').onclick=connect;$('#cloudUpload').onclick=upload;$('#cloudDownload').onclick=download;$('#cloudDisconnect').onclick=()=>{token='';client=null;settings={};saveSettings();$('#cloudActions').hidden=true;status('Disconnected. Local data remains on this device.')};
})();
