const forecastKey='property-ledger-forecasts-v1';
let forecasts=JSON.parse(localStorage.getItem(forecastKey))||[];
forecasts=forecasts.filter(x=>data.properties.some(p=>p.id===x.propertyId));localStorage.setItem(forecastKey,JSON.stringify(forecasts));
const forecast$=s=>document.querySelector(s), forecastMoney=(amount,currency)=>new Intl.NumberFormat(currency==='AED'?'en-AE':'en-GB',{style:'currency',currency:currency||'GBP'}).format(amount||0);
function saveForecasts(){localStorage.setItem(forecastKey,JSON.stringify(forecasts));window.cloudSync?.queue()}
function forecastProperties(){return data.properties}
function renderForecasts(){const id=forecast$('#propertyFilter').value,[from,to]=[forecast$('#forecastFrom').value,forecast$('#forecastTo').value];const entries=forecasts.filter(x=>(id==='all'||x.propertyId===id)&&(!from||x.date>=from)&&(!to||x.date<=to)).sort((a,b)=>a.date.localeCompare(b.date));forecast$('#forecastTable').innerHTML=entries.length?entries.map(x=>{const property=forecastProperties().find(p=>p.id===x.propertyId);return `<tr><td>${x.date}</td><td>${property?.name||'Property removed'}</td><td>${x.description}</td><td class="amount income-text">${forecastMoney(x.amount,property?.currency)}</td><td><button class="delete forecast-delete" data-id="${x.id}" title="Delete forecast">×</button></td></tr>`}).join(''):'<tr><td colspan="5" class="empty">No future rental income is planned for this selection.</td></tr>';document.querySelectorAll('.forecast-delete').forEach(b=>b.onclick=()=>{forecasts=forecasts.filter(x=>x.id!==b.dataset.id);saveForecasts();renderForecasts()})}
function populateForecastProperties(){forecast$('#forecastForm [name=propertyId]').innerHTML=forecastProperties().map(p=>`<option value="${p.id}">${p.name} (${p.currency||'GBP'})</option>`).join('')}
forecast$('#addForecast').onclick=()=>{if(!forecastProperties().length){forecast$('#propertyDialog').showModal();return}const form=forecast$('#forecastForm');form.reset();form.date.value=new Date().toISOString().slice(0,10);populateForecastProperties();const selectedId=forecast$('#propertyFilter').value;if(selectedId!=='all')form.propertyId.value=selectedId;forecast$('#forecastDialog').showModal()};
forecast$('#forecastForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const f=new FormData(e.target);forecasts.push({id:crypto.randomUUID(),propertyId:f.get('propertyId'),date:f.get('date'),description:f.get('description'),amount:Number(f.get('amount'))});saveForecasts();e.target.closest('dialog').close();renderForecasts()};
['#forecastFrom','#forecastTo'].forEach(s=>forecast$(s).onchange=renderForecasts);forecast$('#clearForecastDates').onclick=()=>{forecast$('#forecastFrom').value='';forecast$('#forecastTo').value='';renderForecasts()};forecast$('#propertyFilter').addEventListener('change',renderForecasts);document.querySelector('.nav-link[data-view="forecast"]').addEventListener('click',()=>{forecast$('#pageKicker').textContent='PLANNED RENTAL INCOME';forecast$('#pageTitle').textContent='Forecast';renderForecasts()});document.querySelectorAll('#forecastDialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());renderForecasts();
