const mikeKey='property-ledger-mike-account-v1';
let mikeEntries=JSON.parse(localStorage.getItem(mikeKey))||[];
const mike$=s=>document.querySelector(s), mikeMoney=(amount,currency)=>new Intl.NumberFormat(currency==='AED'?'en-AE':'en-GB',{style:'currency',currency:currency||'GBP'}).format(amount||0);
function saveMike(){localStorage.setItem(mikeKey,JSON.stringify(mikeEntries))}
function mikeTotals(entries){let totals={};entries.forEach(e=>{let currency=data.properties.find(p=>p.id===e.propertyId)?.currency||'GBP';if(!totals[currency])totals[currency]={received:0,charges:0,transfers:0};if(e.type==='received')totals[currency].received+=e.amount;if(e.type==='charge')totals[currency].charges+=e.amount;if(e.type==='transfer')totals[currency].transfers+=e.amount});return totals}
function mikeAmount(totals,key){let values=Object.entries(totals).map(([currency,value])=>mikeMoney(value[key],currency));return values.join(' · ')||mikeMoney(0)}
function renderMike(){let propertyId=mike$('#propertyFilter').value,[from,to]=[mike$('#mikeFrom').value,mike$('#mikeTo').value];let visible=mikeEntries.filter(e=>(propertyId==='all'||e.propertyId===propertyId)&&(!from||e.date>=from)&&(!to||e.date<=to)).sort((a,b)=>b.date.localeCompare(a.date));let totals=mikeTotals(visible);mike$('#mikeReceived').textContent=mikeAmount(totals,'received');mike$('#mikeCharges').textContent=mikeAmount(totals,'charges');mike$('#mikeBalance').textContent=Object.entries(totals).map(([currency,value])=>mikeMoney(value.received-value.charges-value.transfers,currency)).join(' · ')||mikeMoney(0);mike$('#mikeTable').innerHTML=visible.length?visible.map(e=>{let property=data.properties.find(p=>p.id===e.propertyId),labels={received:'Rent received',charge:'Building charge',transfer:'Transferred to you'},negative=e.type!=='received';return `<tr><td>${e.date}</td><td>${property?.name||'Property removed'}</td><td>${e.description}</td><td><span class="type-badge type-${negative?'expense':'income'}">${labels[e.type]}</span></td><td class="amount ${negative?'expense-text':'income-text'}">${negative?'−':'+'}${mikeMoney(e.amount,property?.currency)}</td><td><button class="delete mike-delete" data-id="${e.id}" title="Delete entry">×</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No Mike account entries for this selection.</td></tr>';document.querySelectorAll('.mike-delete').forEach(button=>button.onclick=()=>{mikeEntries=mikeEntries.filter(e=>e.id!==button.dataset.id);saveMike();renderMike()})}
function renderMikeReport(){let propertyId=mike$('#propertyFilter').value,[from,to]=[mike$('#reportFrom').value,mike$('#reportTo').value],entries=mikeEntries.filter(e=>(propertyId==='all'||e.propertyId===propertyId)&&(!from||e.date>=from)&&(!to||e.date<=to)),totals=mikeTotals(entries),name=propertyId==='all'?'All properties':data.properties.find(p=>p.id===propertyId)?.name||'Selected property',summary=Object.entries(totals).map(([currency,value])=>`<div class="report-summary"><div><span>Rent received by Mike</span><strong class="income-text">${mikeMoney(value.received,currency)}</strong></div><div><span>Building charges paid</span><strong class="expense-text">${mikeMoney(value.charges,currency)}</strong></div><div><span>Transferred to you</span><strong class="expense-text">${mikeMoney(value.transfers,currency)}</strong></div><div><span>Balance held by Mike</span><strong>${mikeMoney(value.received-value.charges-value.transfers,currency)}</strong></div></div>`).join('')||'<p class="empty">No Mike account activity in this period.</p>';mike$('#mikeReportArea').innerHTML=`<div class="report-title"><h2>${name}</h2><p>${from||'Beginning'} to ${to||'Today'}</p></div>${summary}`}
function populateMikeProperties(){mike$('#mikeForm [name=propertyId]').innerHTML=data.properties.map(p=>`<option value="${p.id}">${p.name} (${p.currency||'GBP'})</option>`).join('')}
mike$('#addMikeEntry').onclick=()=>{if(!data.properties.length){mike$('#propertyDialog').showModal();return}let form=mike$('#mikeForm');form.reset();form.date.value=new Date().toISOString().slice(0,10);populateMikeProperties();let selectedId=mike$('#propertyFilter').value;if(selectedId!=='all')form.propertyId.value=selectedId;mike$('#mikeDialog').showModal()};
mike$('#mikeForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();let f=new FormData(e.target);mikeEntries.push({id:crypto.randomUUID(),propertyId:f.get('propertyId'),date:f.get('date'),type:f.get('type'),amount:Number(f.get('amount')),description:f.get('description')});saveMike();e.target.closest('dialog').close();renderMike()};
['#mikeFrom','#mikeTo'].forEach(selector=>mike$(selector).onchange=renderMike);mike$('#clearMikeDates').onclick=()=>{mike$('#mikeFrom').value='';mike$('#mikeTo').value='';renderMike()};mike$('#propertyFilter').addEventListener('change',()=>{renderMike();renderMikeReport()});document.querySelector('.nav-link[data-view="mike"]').addEventListener('click',()=>{mike$('#pageKicker').textContent='FUNDS HELD BY MIKE';mike$('#pageTitle').textContent='Mike account';renderMike()});document.querySelector('.nav-link[data-view="reports"]').addEventListener('click',renderMikeReport);mike$('#runReport').addEventListener('click',renderMikeReport);document.querySelectorAll('#mikeDialog .close').forEach(button=>button.onclick=()=>button.closest('dialog').close());renderMike();renderMikeReport();
